sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  hosts:
    - docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - docker save -o $HOME/docker_cache/docker.tar stfdigital-autuacao-recebimento $(docker history -q stfdigital-autuacao-recebimento | tail -n +2 | grep -v \<missing\> | tr '\n' ' ')
cache:
  directories:
    - $HOME/.gradle/caches/
    - node_cache
    - node_modules
    - $HOME/docker_cache
before_install:
  - ./upgrade-docker.sh
  - docker-compose -f docker-compose.yml -f docker-compose-e2e.yml pull &
  - COMPOSE_PULL_PID=$!
  - echo $COMPOSE_PULL_PID
  - mkdir -p $HOME/docker_cache
install: docker load -i $HOME/docker_cache/docker.tar || true
script:
  - gradle docker && gradle gulpTestUnit && (wait $COMPOSE_PULL_PID || true) && ./test-e2e.sh