sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  hosts:
    - docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - docker save stfdigital-autuacao-recebimento $(docker history -q stfdigital-autuacao-recebimento | tail -n +2 | grep -v \<missing\> | tr '\n' ' ') -o $HOME/docker_cache/docker.tar
cache:
  directories:
    - $HOME/.gradle/caches/
    - node_cache
    - node_modules
    - $HOME/docker_cache
before_install:
  - ./upgrade-docker.sh
  - mkdir -p $HOME/docker_cache
install: docker load -i $HOME/docker_cache/docker.tar || true
script: gradle docker && gradle gulpTestUnit && ./test-e2e.sh