sudo: required
language: java
jdk:
  - oraclejdk8
services:
- docker
install:
  - git clone https://github.com/supremotribunalfederal/stfdigital-plataforma-core
  - cd stfdigital-plataforma-core
  - gradle install
  - cd -
script: gradle docker && gradle gulp_test