sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  hosts:
    - docker
before_install: ./upgrade-docker.sh
install: true
script: gradle docker && gradle gulpTestUnit && ./test-e2e.sh