sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  hosts:
    - docker
    - eti078082
before_install: ./upgrade-docker.sh
install:
  - git clone https://github.com/supremotribunalfederal/stfdigital-plataforma-core
  - cd stfdigital-plataforma-core
  - gradle install
  - cd -
script: gradle docker && gradle gulpTestUnit && ./test-e2e.sh