sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  hosts:
    - docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - node_cache
    - node_modules
before_install: ./upgrade-docker.sh
install: true
#script: gradle docker && gradle gulpTestUnit && ./test-e2e.sh
script: gradle docker && gradle gulpTestUnit
#