sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  hosts:
    - docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - docker save recebimento $(docker history -q recebimento | tail -n +2 | grep -v \<missing\> | tr '\n' ' ') | gzip > $HOME/docker_cache/docker.tar.gz
cache:
  directories:
    - $HOME/.gradle/caches/
    - node_cache
    - node_modules
    - $HOME/docker_cache
before_install:
  - ./upgrade-docker.sh
  - mkdir -p $HOME/docker_cache
install: tar -xzf $HOME/docker_cache/docker.tar.gz | docker load -i || true
#script: gradle docker && gradle gulpTestUnit && ./test-e2e.sh
script: gradle docker && gradle gulpTestUnit
#