# Define a configuração para rodar com imagens locais
version: '2'
volumes:
  logs:
    driver: local
services:
  rabbit:
    extends:
      file: shared/compose/common.yml
      service: rabbit
  discovery:
    extends:
      file: shared/compose/common.yml
      service: discovery
    image: stfdigital-plataforma-discovery
  gateway:
    extends:
      file: shared/compose/common.yml
      service: gateway
    image: stfdigital-plataforma-gateway
    depends_on:
     - discovery
  services:
    extends:
      file: shared/compose/common.yml
      service: services
    image: stfdigital-plataforma-services
    depends_on:
     - rabbit
     - discovery
  ui:
    extends:
      file: shared/compose/common.yml
      service: ui
    image: stfdigital-plataforma-ui
    depends_on:
     - gateway
  userauthentication:
    extends:
      file: shared/compose/common.yml
      service: userauthentication
    image: stfdigital-plataforma-userauthentication
    depends_on:
     - rabbit
     - discovery
  cassandra:
    extends:
      file: shared/compose/common.yml
      service: cassandra
  onlyoffice:
    extends:
      file: shared/compose/common.yml
      service: onlyoffice_ambassador
  documents:
    extends:
      file: shared/compose/common.yml
      service: documents
    image: stfdigital-plataforma-documents
    links:
     - onlyoffice:docker # documents precisa acessar o onlyoffice pelo host docker para não dar erro de certificado
    depends_on:
     - cassandra
     - rabbit
     - discovery
     - onlyoffice