version: '2'
services:
  discovery:
    mem_limit: 500000000
    environment:
     - JAVA_OPTS=-Xmx512m
  gateway:
    ports:
     - "8765:8765"
  services:
    mem_limit: 500000000
    environment:
     - JAVA_OPTS=-Xmx512m
  documents:
    command: --onlyoffice.documentserver.host=docker --onlyoffice.documentserver.protocol=https
    mem_limit: 500000000
    environment:
     - JAVA_OPTS=-Xmx512m
    environment:
     - spring.profiles.active=development
  ui:
    ports:
     - "8443:8443"
  recebimento:
    container_name: recebimento
    image: recebimento
    mem_limit: 500000000
    environment:
     - JAVA_OPTS=-Xmx512m
    environment:
     - spring.profiles.active=development,e2e
    depends_on:
     - rabbit
     - discovery
  onlyoffice:
    container_name: onlyoffice
    image: supremotribunalfederal/onlyofficeds
    ports:
     - "443:443"
    stdin_open: true
    mem_limit: 2000000000
    environment:
     - JAVA_OPTS=-Xmx512m
    environment:
     - SSL_CERTIFICATE_PATH=/certs/docker/onlyoffice.crt
     - SSL_KEY_PATH=/certs/docker/onlyoffice.key
     - SSL_DHPARAM_PATH=/certs/docker/dhparam.pem