version: '2'
services:
  discovery:
    ports:
     - "8761:8761"
    environment:
     - JAVA_OPTS=-Xmx512m -Xms512m
  gateway:
    ports:
     - "8765:8765"
  services:
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xmx512m -Xms512m
  documents:
    environment:
     - JAVA_OPTS=-Xmx512m -Xms512m
     - spring.profiles.active=development
     - onlyoffice.documentserver.host=gateway
     - onlyoffice.server.address=https://docker:443
  ui:
    ports:
     - "8443:8443"
  recebimento:
    container_name: recebimento
    image: stfdigital-autuacao-recebimento
    environment:
     - JAVA_OPTS=-Xmx512m -Xms512m
    environment:
     - spring.profiles.active=development,e2e
    depends_on:
     - rabbit
     - discovery
  onlyoffice:
    container_name: onlyoffice
    image: supremotribunalfederal/onlyofficeds
    ports:
     - "443:443"
    stdin_open: true
    mem_limit: 2000000000
    environment:
     - SSL_CERTIFICATE_PATH=/certs/docker/onlyoffice.crt
     - SSL_KEY_PATH=/certs/docker/onlyoffice.key
     - SSL_DHPARAM_PATH=/certs/docker/dhparam.pem
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:2.53.0
    ports:
     - "4444:4444"
    depends_on:
     - docker
  docker:
    container_name: docker-ambassador
    image: svendowideit/ambassador
    environment:
     - UI_PORT_8443_TCP=tcp://ui:8443
     - GATEWAY_PORT_8765_TCP=tcp://gateway:8765
     - ONLYOFFICE_PORT_443=tcp://onlyoffice:443
    depends_on:
     - ui
     - gateway
     - onlyoffice