version: '2'
services:
  recebimento:
    container_name: recebimento
    image: recebimento
    ports:
     - "8091:8091"
     - "8191:8191"
     - "47991:47991"
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47991,suspend=n
    depends_on:
     - rabbit
     - discovery