version: '2'
services:
  gateway:
    ports:
     - "8765:8765"
  documents:
    command: --onlyoffice.documentserver.host=eti078082 --onlyoffice.documentserver.protocol=https
    environment:
     - spring.profiles.active=development
  ui:
    ports:
     - "8443:8443"
  recebimento:
    container_name: recebimento
    image: recebimento
    environment:
     - spring.profiles.active=development,e2e
    depends_on:
     - rabbit
     - discovery