version: '2'
services:
  onlyoffice:
    container_name: onlyoffice
    image: supremotribunalfederal/onlyofficeds
    ports:
     - "443:443"
    stdin_open: true
    environment:
     - SSL_CERTIFICATE_PATH=/certs/docker/onlyoffice.crt
     - SSL_KEY_PATH=/certs/docker/onlyoffice.key
     - SSL_DHPARAM_PATH=/certs/docker/dhparam.pem