version: '2'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
  discovery:
    container_name: discovery
    image: supremotribunalfederal/stfdigital-plataforma-discovery
    ports:
     - "8761:8761"
     - "47961:47961"
    environment:
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47961,suspend=n
  gateway:
    container_name: gateway
    image: supremotribunalfederal/stfdigital-plataforma-gateway
    ports:
     - "8765:8765"
     - "47965:47965"
    environment:
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47965,suspend=n
    depends_on:
     - discovery     
  services:
    container_name: services
    image: supremotribunalfederal/stfdigital-plataforma-services
    ports:
     - "8081:8081"
     - "8181:8181"
     - "47981:47981"
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47981,suspend=n
    depends_on:
     - rabbit
     - discovery     
  mongo:
    container_name: mongo
    image: mongo:3
    ports:
     - "27017:27017"
  documents:
    container_name: documents
    image: supremotribunalfederal/stfdigital-plataforma-documents
    command: --onlyoffice.documentserver.host=eti078143 --onlyoffice.documentserver.protocol=https
    ports:
     - "8094:8094"
     - "8194:8194"
     - "47994:47994"
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47994,suspend=n
    depends_on:
     - mongo
     - discovery
  ui:
    container_name: ui
    image: supremotribunalfederal/stfdigital-plataforma-ui
    ports:
     - "8443:8443"
    depends_on:
     - discovery