version: '2'
services:
  gateway:
    ports:
     - "8765:8765"
  documents:
    command: --onlyoffice.documentserver.host=docker --onlyoffice.documentserver.protocol=https
    environment:
     - spring.profiles.active=development
  ui:
    ports:
     - "8443:8443"
  recebimento:
    container_name: recebimento
    image: recebimento
    environment:
     - spring.profiles.active=development,e2e
    depends_on:
     - rabbit
     - discovery
  onlyoffice:
    container_name: onlyoffice
    image: stf/onlyofficeds-runner
    ports:
     - "443:443"
    stdin_open: true
    environment:
     - SSL_CERTIFICATE_PATH=/certs/docker/onlyoffice.crt
     - SSL_KEY_PATH=/certs/docker/onlyoffice.key
     - SSL_DHPARAM_PATH=/certs/docker/dhparam.pem