server:
  port: 8091

spring:
  application:
    name: recebimento
  datasource:
    url: jdbc:h2:mem:recebimento;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ 
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    
flyway:
  validate-on-migrate: false
  
http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit
      
security:
  oauth2:
    client:
      clientId: peticionamento
      clientSecret: peticionamento
      accessTokenUri: http://localhost:8095/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8095/user
            