# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  recebimento:
    extends:
      file: shared/compose/common.yml
      service: recebimento
    image: stfdigital-autuacao-recebimento
    depends_on:
     - rabbit
     - discovery